### ISSUE TITLE
About the results in Table 5

### ISSUE THREAD

**Issue by LinkToPast1900** [VITA-Group/SDCLR#1]
Hi, @geekJZY, thanks for your great work.
I have a question about the results in Table 5.

![image](https://user-images.githubusercontent.com/85857950/121835290-6ea78380-cd03-11eb-99c4-aa64abd4018f.png)

![image](https://user-images.githubusercontent.com/85857950/121835238-4f105b00-cd03-11eb-805f-f007260a255a.png)

It seems that in Table 5, the results of SimCLR are obtained on long-tail subset D_i of CIFAR10 and CIFAR100, while the results of SDCLR are obtained from the full dataset of CIFAR10 and CIFAR100. 

If so, could we compare these two sets of results as shown in Table 5?

Thanks!

**Comment by geekJZY** [comment]
Both SimCLR and SDCLR are pre-trained on D_i of CIFAR10 and CIFAR100. You can refer to the few-shot evaluation protocol for more details.

**Comment by LinkToPast1900** [comment]
Thanks! So the CIFAR10 and CIFAR100 are CIFAR10-LT and CIFAR100-LT as Table 4? 
![image](https://user-images.githubusercontent.com/85857950/121836369-dd85dc00-cd05-11eb-932a-2703fb56280a.png)

**Comment by geekJZY** [comment]
Yes, it should be CIFAR-10-LT and CIFAR-100-LT here. Sorry for not making it clear.
